[build]
  command = "yarn build"
  publish = "dist/celeste-search"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "https://celeste-search.netlify.com/*"
  to = "https://search.projectceleste.com/:splat"
  status = 301
  force = true
