[[redirects]]
  from = "https://celeste-search.netlify.com/*"
  to = "https://search.projectceleste.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*.css"
[headers.values]
  Cache-Control = "max-age=31536000, public, immutable"

[[headers]]
  for = "/*.js"
[headers.values]
  Cache-Control = "max-age=31536000, public, immutable"

[[headers]]
  for = "/assets/meta/app-16.png"
  [headers.values]
    Access-Control-Allow-Origin = "*"
