[[redirects]]
  from = "https://search.projectceleste.com/*"
  to = "https://celeste-search.netlify.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*.css"
[headers.values]
  Cache-Control = "max-age=31536000, public, immutable"

[[headers]]
  for = "/*.js"
[headers.values]
  Cache-Control = "max-age=31536000, public, immutable"

[[headers]]
  for = "/assets/meta/app-16.png"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, HEAD, OPTIONS"
    Access-Control-Allow-Headers = "DNT, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type, Range"
