[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "https://celeste-search.netlify.com/*"
  to = "https://search.projectceleste.com/:splat"
  status = 308
  force = true
